### ISSUE TITLE
Compare two blocks is bad practice

### ISSUE THREAD

**Issue by Lweek** [fcanas/Formulary#15]
Hi, I tried fork Formulary and convert it to Swift 2. Everything went quite smooth except line 95 in Cell.swift where you compare two closures. It is not supported in Swift 2.0 and generally it is not very good practice. So it would be better to set empty action as nil and check it out before calling that closure wherever it is called.

Check this out:
http://stackoverflow.com/a/25694072/1441957

Best regards, Vlad

**Comment by fcanas** [comment]
@Lweek 

When I look at line 95, I see

``` swift
ActionTarget(control: button, controlEvents: UIControlEvents.TouchUpInside, action: row.action ?? emptyAction)
```

https://github.com/fcanas/Formulary/blob/master/Formulary/Forms/Cell.swift#L95

Which checks whether `row.action` is `nil` and passes `emptyAction` as an argument instead if it is. I don't think that's a problem, but I also don't think that's what you're referring to.

Could you elaborate by putting a link to the offending line or by copying the line out in this issue? I'm sure there's a simple way around it.

**Comment by Lweek** [comment]
@fcanas Oh I see. You're right I'm sorry, my fault. Xcode was referring to operator ?? as a binary operator. It didn't hit me. I had to replace it with classic ternary operator. 

Thank you!

**Comment by fcanas** [comment]
I can't tell if the unavailability of the nil coalescing operator (`??`) on functions is deliberate or not. This might be a Swift bug; but it's still present in the GM. I'm going to look into it a bit more and maybe file a radar. 

In any case, #16 should be of interest to you.
