### ISSUE TITLE
Not working on swift 2.0? 

### ISSUE THREAD

**Issue by fnk0** [fcanas/Formulary#17]
I'm using Xcode 7 (Version 7.0.1 (7A1001)) with latest swift but it doesn't seem to want compile. 
Using => `pod 'Formulary', '~>' 0.2`
![error](http://i61.tinypic.com/20sjarq.png)

**Comment by fcanas** [comment]
It will totally work if you point your pod at the repositories head. I will try and get a release out in the next couple of days.

**Comment by fnk0** [comment]
What would the line on my pod file look like? (Sorry Android dev here learning iOS) :)

**Comment by fcanas** [comment]
The line would look like this

```
pod 'Formulary', :git => 'https://github.com/fcanas/Formulary.git', :commit => '79b2955555e96b1e094e76d6d89c739add0ad8ec'
```

I don't know about the rest of your Podfile.

I'll try to get a `0.3.0` out this week and you can revert back to referring to the pod as normal.

**Comment by fcanas** [comment]
I'm leaving this issue open until I make a compatible release.

:dancers:

**Comment by fnk0** [comment]
Thank you! Yeah I only needed that line. I knew I could point pods to branch's but I didn't knew that I could point to a specific commit. It's good to know :)

**Comment by fcanas** [comment]
We now have a lovely [v0.3.0](https://github.com/fcanas/Formulary/releases/tag/v0.3.0) release! :tada:
